version: "3"
services:
  db:
    container_name: maria_items
    restart: always
    image: "mariadb:latest"
    environment:
      - MARIADB_USER=user
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - 1234:3306
    networks:
      - backend
    volumes:
      - ./../Data:/var/lib/mysql
#volumes: mariadb
networks:
  backend:
    driver: bridge
